name: GitHub Actions Demo
on:  [push]
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create test coverage directory
        run: mkdir -p ${{ github.workspace }}/.coverage

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.18'
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0

      - name: Run tests and generate coverage
        run:  go test ./... -race -coverprofile=${{ github.workspace }}/.coverage/coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ${{ github.workspace }}/.coverage/coverage.out
          flags: unittests
          verbose: true

  deploy-to-aws-lambda:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get Hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Create build directory
        run: mkdir -p ${{ github.workspace }}/.build

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.18'
          check-latest: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-south-1

      - name: Generate the binary
        run: GOOS=linux GOARCH=amd64 go build -o ${{ env.build_path }}/build_${{ env.hash }} main.go

      - name: Upload the binary to AWS Lambda
        run: |
          zip ${{ github.workspace }}/.build/build_${{ env.hash }}.zip ${{ github.workspace }}/.build/build_${{ env.git_hash }}
          aws lambda update-function-code --function-name=githubActions --zip-file=fileb://${{ github.workspace }}/.build/build_${{ env.git_hash }}.zip
