name: GitHub Actions Demo
on:  [push]
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.18'
          check-latest: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
      - name: Run tests and generate coverage
        run:  mkdir -p /home/runner/coverage/reports && go test -race -coverprofile=/home/runner/coverage/reports/coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./.coverage/reports/coverage.out
          flags: unittests
          verbose: true
